# Generated by Django 2.0.3 on 2018-03-12 18:23

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171107_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(verbose_name='заметка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=markdownx.models.MarkdownxField(verbose_name='предпросмотр'),
        ),
    ]
